import {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from "react";

type Language =
  | "en"
  | "es"
  | "fr"
  | "de"
  | "it"
  | "pt"
  | "hi"
  | "zh"
  | "ja"
  | "ar"
  | "ne";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Stay With Me",
    home: "Home",
    confess: "Confession Box",
    journal: "Journal",
    moodTracker: "Mood Tracker",
    emergency: "Emergency Resources",
    writeLetter: "Write a Letter",
    readLetters: "Read Letters",
    login: "Login",
    logout: "Logout",
    signup: "Sign Up",
    firstName: "First Name",
    lastName: "Last Name",
    useAnonymousName: "I prefer to use an anonymous name",
    anonymousName: "Anonymous/Fake Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    dataSafetyMessage:
      "We care for you and your information. Your data will be safe with us.",
    reasonsToStayAlive: "Reasons to Stay Alive",
    uploadPhotos: "Upload Photos of Loved Ones",
    footerMessage:
      "We care about you. Don't give up - you are meaningful and loved.",
    welcome: "You're not alone",
    welcomeSubtitle:
      "A safe space for your thoughts and feelings",
    confessTitle: "Confession Box",
    confessSubtitle: "Share what's on your mind, anonymously",
    withAI: "With AI Support",
    withoutAI: "Without AI",
    enterConfession: "Write your thoughts here...",
    submit: "Submit",
    journalTitle: "My Journal",
    enterPin: "Enter 4-digit PIN",
    unlock: "Unlock",
    moodTitle: "How are you feeling today?",
    emergencyTitle: "Emergency Resources",
    calmingExercises: "Calming Exercises",
    breathingExercise: "Breathing Exercise",
    guidedMeditation: "Guided Meditation",
    writeLetterTitle: "Write a Letter",
    writeLetterSubtitle:
      "Share positivity with someone who needs it",
    readLettersTitle: "Letters from Friends",
    confidentialityPromise:
      "We promise to keep everything you share here confidential and secure.",
    termsAndConditions:
      "By using this service, you agree to our Terms and Conditions",
    deleteNow: "Delete Now",
    deleteAfter1Hour: "Delete after 1 hour",
    deleteAfter1Week: "Delete after 1 week",
    deleteAfter1Month: "Delete after 1 month",
    aiResponse:
      "Remember, you're stronger than you think. Every step forward, no matter how small, is progress.",
    crisisMessage:
      "If you're having thoughts of self-harm, please reach out for help immediately.",
    nickname: "Nickname",
    invalidEmailError: "Please enter a valid email address",
    enterPasswordError: "Please enter your password",
    welcomeBack: "Welcome back!",
    enterFirstLastError: "Please enter your first and last name",
    enterAnonymousNameError: "Please enter an anonymous name",
    passwordPolicyError:
      "Password must be at least 8 characters with uppercase, lowercase, number, and special character",
    passwordsDoNotMatch: "Passwords do not match",
    agreeTermsError: "Please agree to the terms and conditions",
    signinSubtitle: "Sign in to your account",
    signupSubtitle: "Create your safe space account",
    emailPlaceholder: "your.email@example.com",
    passwordPlaceholder: "••••••••",
    firstNamePlaceholder: "First name",
    lastNamePlaceholder: "Last name",
    anonymousNamePlaceholder: "Phoenix, Shadow, etc.",
    passwordRulesHint: "Min 8 chars, A-Z, a-z, 0-9, @$!%*?&",
    confirmPasswordPlaceholder: "Re-enter password",
    authPrivacyFooter:
      "Your email is only used for authentication. You'll be identified by a random nickname.",
    homePositiveMessage: "You are stronger than you know",
    homeJournalDesc: "Private, secure journal with PIN protection",
    homeMoodDesc: "Track your emotional journey",
    homeEmergencyDesc: "Breathing exercises and calming resources",
    homeReasonsDesc: "Remember what makes life beautiful",
    homeReadLettersDesc: "Read encouraging messages from others",
    homeSafeSpaceTitle: "Your Safe Space",
    homeSafeSpaceSubtitle: "Choose the support you need, whenever you need it",
    pleaseSelectMood: "Please select a mood",
    moodTracked: "Mood tracked!",
    selectYourMood: "Select your mood",
    addNoteOptional: "Add a note (optional)",
    whatsOnYourMind: "What's on your mind?",
    saveMood: "Save Mood",
    yourMoodHistory: "Your Mood History",
    noMoodEntriesYet: "No mood entries yet. Start tracking!",
    moodGreat: "Great",
    moodGood: "Good",
    moodOkay: "Okay",
    moodBad: "Bad",
    moodTerrible: "Terrible",
    pinMustBe4Digits: "PIN must be 4 digits",
    journalPinSetSuccess: "Journal PIN set successfully",
    incorrectPin: "Incorrect PIN",
    pleaseWriteSomething: "Please write something",
    entrySaved: "Entry saved",
    entryDeleted: "Entry deleted",
    youAreNotAloneReachOut: "You're not alone. Please reach out to someone who can help.",
    viewEmergencyResources: "View Emergency Resources",
    goBack: "Go Back",
    journalPrivateSecureSpace: "Your private, secure space",
    enterPinToAccessJournal: "Enter your PIN to access your journal",
    setPinToProtectJournal: "Set a 4-digit PIN to protect your journal",
    lock: "Lock",
    journalSanctuary: "Your thoughts, your sanctuary",
    newEntry: "New Entry",
    writeThoughtsHere: "Write your thoughts here...",
    addEntry: "Add Entry",
    noEntriesYetStartWriting: "No entries yet. Start writing!",
    pleaseWriteAtLeast20Chars: "Please write at least 20 characters",
    positiveWordsOnly: "Please use only positive and encouraging words",
    anonymous: "Anonymous",
    letterSharedSuccess: "Your letter has been shared! Thank you for spreading positivity.",
    writeYourLetter: "Write Your Letter",
    writeLetterGuidance:
      "Share words of encouragement, hope, and positivity. Your letter could brighten someone's day when they need it most.",
    writeLetterPlaceholder: "Dear friend,\n\nI want you to know that...",
    charactersMinimum20: "characters (minimum 20)",
    fromLabel: "From:",
    guidelines: "Guidelines:",
    guidelinePositiveWords: "Use only positive and encouraging words",
    guidelineGenuine: "Be genuine and heartfelt",
    guidelineFriendInNeed: "Imagine you're writing to a friend in need",
    guidelineAnonymousShare: "Your letter will be shared anonymously with your nickname",
    sendLetter: "Send Letter",
    readLettersFromOthers: "Read Letters from Others",
    noLettersYet: "No Letters Yet",
    beFirstToSharePositivity: "Be the first to share some positivity!",
    readLettersSubtitle: "Messages of hope from strangers who care",
    previous: "Previous",
    random: "Random",
    next: "Next",
    shareOwnMessageCta: "Want to share your own message of hope?",
    maxPhotosError: "You can upload a maximum of {max} photos",
    photosUploaded: "Photos uploaded!",
    reasonsSubtitle: "Remember the beautiful moments and people that make life worth living",
    uploadPhotosHelp:
      "Upload photos of your loved ones, pets, favorite places, or anything that brings you joy and reminds you why life is precious.",
    choosePhotos: "Choose Photos",
    continueToVideos: "Continue to Inspirational Videos",
    wordsOfHope: "Words of Hope and Encouragement",
    wordsOfHopeDesc:
      "Watch these powerful messages about hope, resilience, and why your life matters.",
    footerStrengthLine:
      "You are stronger than you think, braver than you believe, and more loved than you know.",
    youMatterTitle: "You Matter",
    youMatterDesc: "Your life has value and purpose, even when it's hard to see",
    youreNotAloneTitle: "You're Not Alone",
    youreNotAloneDesc:
      "We're here for you, and there are people who care deeply about you",
    hopeExistsTitle: "Hope Exists",
    hopeExistsDesc: "Things can and will get better. Tomorrow is a new opportunity",
    ifInCrisisReachOut: "If you're in crisis, please reach out:",
    safeSpaceMentalHealth: "A safe space for mental health support",
    footerQuote:
      "\"In the midst of winter, I found there was, within me, an invincible summer.\" - Albert Camus",
    pinSetSuccess: "PIN set successfully",
    enterPinToAccess: "Enter your PIN to access",
    setPinToProtectConfessions: "Set a 4-digit PIN to protect your confessions",
    chooseYourMode: "Choose Your Mode",
    withAIDesc: "Get encouraging AI-powered responses",
    withoutAIDesc: "Simply share your thoughts privately",
    deleteOption: "Delete Option",
    back: "Back",
    heresSomethingForYou: "Here's something for you",
    letterFromFriendTitle: "A Letter From a Friend",
    dearFriend: "Dear friend,",
    friendLetterPara1:
      "I want you to know that whatever you're going through right now, you're not alone. Your feelings are valid, and it's okay to not be okay sometimes.",
    friendLetterPara2:
      "Remember that storms don't last forever. Even on the darkest days, there's light waiting to break through. You are stronger than you realize, and you deserve kindness - especially from yourself.",
    friendLetterPara3: "Take it one moment at a time. Breathe. You've got this.",
    friendLetterSignature: "With hope and support,\nA Friend Who Cares",
    aiSupportMessage: "AI Support Message",
    goHome: "Go Home",
    newConfession: "New Confession",
    emergencySubtitle: "Tools to help you find calm and peace",
    ifInCrisis: "If you're in crisis",
    pleaseReachImmediateHelp: "Please reach out for immediate help. You're not alone.",
    boxBreathingTitle: "Box Breathing (4-4-4-4)",
    boxBreathingDesc: "Used by Navy SEALs to stay calm under pressure",
    breatheIn: "Breathe In",
    hold: "Hold",
    breatheOut: "Breathe Out",
    fourSeconds: "4 seconds",
    stop: "Stop",
    start: "Start",
    howItWorks: "How it works:",
    breatheIn4: "Breathe in for 4 seconds",
    hold4: "Hold your breath for 4 seconds",
    breatheOut4: "Breathe out for 4 seconds",
    rest4: "Rest for 4 seconds (implied in the cycle)",
    repeatAsNeeded: "Repeat as needed",
  },
  es: {
    appName: "Quédate Conmigo",
    home: "Inicio",
    confess: "Caja de Confesiones",
    journal: "Diario",
    moodTracker: "Seguimiento del Estado de Ánimo",
    emergency: "Recursos de Emergencia",
    writeLetter: "Escribir una Carta",
    readLetters: "Leer Cartas",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    signup: "Registrarse",
    firstName: "Nombre",
    lastName: "Apellido",
    useAnonymousName: "Prefiero usar un nombre anónimo",
    anonymousName: "Nombre Anónimo/Falso",
    email: "Correo Electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    createAccount: "Crear Cuenta",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿No tienes una cuenta?",
    dataSafetyMessage:
      "Nos preocupamos por ti y tu información. Tus datos estarán seguros con nosotros.",
    reasonsToStayAlive: "Razones para Seguir Viviendo",
    uploadPhotos: "Subir Fotos de Seres Queridos",
    footerMessage:
      "Nos importas. No te rindas - eres valioso y amado.",
    welcome: "No estás solo",
    welcomeSubtitle:
      "Un espacio seguro para tus pensamientos y sentimientos",
    confessTitle: "Caja de Confesiones",
    confessSubtitle:
      "Comparte lo que tienes en mente, de forma anónima",
    withAI: "Con Soporte de IA",
    withoutAI: "Sin IA",
    enterConfession: "Escribe tus pensamientos aquí...",
    submit: "Enviar",
    journalTitle: "Mi Diario",
    enterPin: "Ingresa PIN de 4 dígitos",
    unlock: "Desbloquear",
    moodTitle: "¿Cómo te sientes hoy?",
    emergencyTitle: "Recursos de Emergencia",
    calmingExercises: "Ejercicios Calmantes",
    breathingExercise: "Ejercicio de Respiración",
    guidedMeditation: "Meditación Guiada",
    writeLetterTitle: "Escribir una Carta",
    writeLetterSubtitle:
      "Comparte positividad con alguien que lo necesita",
    readLettersTitle: "Cartas de Amigos",
    confidentialityPromise:
      "Prometemos mantener todo lo que compartes aquí confidencial y seguro.",
    termsAndConditions:
      "Al usar este servicio, aceptas nuestros Términos y Condiciones",
    deleteNow: "Eliminar Ahora",
    deleteAfter1Hour: "Eliminar después de 1 hora",
    deleteAfter1Week: "Eliminar después de 1 semana",
    deleteAfter1Month: "Eliminar después de 1 mes",
    aiResponse:
      "Recuerda, eres más fuerte de lo que piensas. Cada paso adelante, por pequeño que sea, es progreso.",
    crisisMessage:
      "Si tienes pensamientos de autolesión, busca ayuda de inmediato.",
    nickname: "Apodo",
    letterFromFriendTitle: "Una carta de un amigo",
    dearFriend: "Querido amigo,",
    friendLetterPara1:
      "Quiero que sepas que, sea lo que sea que estés pasando ahora mismo, no estás solo. Tus sentimientos son válidos, y a veces está bien no estar bien.",
    friendLetterPara2:
      "Recuerda que las tormentas no duran para siempre. Incluso en los días más oscuros, hay luz esperando salir. Eres más fuerte de lo que crees y mereces amabilidad, especialmente de ti mismo.",
    friendLetterPara3: "Tómalo un momento a la vez. Respira. Tú puedes con esto.",
    friendLetterSignature: "Con esperanza y apoyo,\nUn amigo que se preocupa",
  },
  fr: {
    appName: "Reste Avec Moi",
    home: "Accueil",
    confess: "Boîte de Confession",
    journal: "Journal",
    moodTracker: "Suivi de l'Humeur",
    emergency: "Ressources d'Urgence",
    writeLetter: "Écrire une Lettre",
    readLetters: "Lire les Lettres",
    login: "Connexion",
    logout: "Déconnexion",
    signup: "S'inscrire",
    firstName: "Prénom",
    lastName: "Nom de famille",
    useAnonymousName: "Je préfère utiliser un nom anonyme",
    anonymousName: "Nom Anonyme/Faux",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    createAccount: "Créer un compte",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    dataSafetyMessage:
      "Nous nous soucions de vous et de vos informations. Vos données seront en sécurité avec nous.",
    reasonsToStayAlive: "Raisons de Rester Vivant",
    uploadPhotos: "Télécharger des Photos de Personnes Aimées",
    footerMessage:
      "Nous nous soucions de vous. Ne vous donnez pas - vous êtes significatif et aimé.",
    welcome: "Tu n'es pas seul",
    welcomeSubtitle:
      "Un espace sûr pour tes pensées et sentiments",
    confessTitle: "Boîte de Confession",
    confessSubtitle: "Partage ce qui te préoccupe, anonymement",
    withAI: "Avec Support IA",
    withoutAI: "Sans IA",
    enterConfession: "Écris tes pensées ici...",
    submit: "Soumettre",
    journalTitle: "Mon Journal",
    enterPin: "Entrez le code PIN à 4 chiffres",
    unlock: "Déverrouiller",
    moodTitle: "Comment te sens-tu aujourd'hui?",
    emergencyTitle: "Ressources d'Urgence",
    calmingExercises: "Exercices Calmants",
    breathingExercise: "Exercice de Respiration",
    guidedMeditation: "Méditation Guidée",
    writeLetterTitle: "Écrire une Lettre",
    writeLetterSubtitle:
      "Partage de la positivité avec quelqu'un qui en a besoin",
    readLettersTitle: "Lettres d'Amis",
    confidentialityPromise:
      "Nous promettons de garder tout ce que tu partages ici confidentiel et sécurisé.",
    termsAndConditions:
      "En utilisant ce service, tu acceptes nos Termes et Conditions",
    deleteNow: "Supprimer Maintenant",
    deleteAfter1Hour: "Supprimer après 1 heure",
    deleteAfter1Week: "Supprimer après 1 semaine",
    deleteAfter1Month: "Supprimer après 1 mois",
    aiResponse:
      "Souviens-toi, tu es plus fort que tu ne le penses. Chaque pas en avant, aussi petit soit-il, est un progrès.",
    crisisMessage:
      "Si tu as des pensées d'automutilation, demande de l'aide immédiatement.",
    nickname: "Surnom",
    letterFromFriendTitle: "Une lettre d'un ami",
    dearFriend: "Cher ami,",
    friendLetterPara1:
      "Je veux que tu saches que quoi que tu traverses en ce moment, tu n'es pas seul. Tes émotions sont valides, et c'est parfois normal de ne pas aller bien.",
    friendLetterPara2:
      "Rappelle-toi que les tempêtes ne durent pas toujours. Même dans les jours les plus sombres, une lumière finit par apparaître. Tu es plus fort que tu ne le penses, et tu mérites de la bienveillance, surtout envers toi-même.",
    friendLetterPara3: "Prends les choses un moment à la fois. Respire. Tu vas y arriver.",
    friendLetterSignature: "Avec espoir et soutien,\nUn ami qui tient à toi",
  },
  de: {
    appName: "Bleib Bei Mir",
    home: "Startseite",
    confess: "Beichtbox",
    journal: "Tagebuch",
    moodTracker: "Stimmungs-Tracker",
    emergency: "Notfall-Ressourcen",
    writeLetter: "Brief Schreiben",
    readLetters: "Briefe Lesen",
    login: "Anmelden",
    logout: "Abmelden",
    signup: "Registrieren",
    firstName: "Vorname",
    lastName: "Nachname",
    useAnonymousName: "Ich bevorzuge einen anonymen Namen",
    anonymousName: "Anonymer/Falscher Name",
    email: "E-Mail",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    createAccount: "Konto erstellen",
    alreadyHaveAccount: "Hast du bereits ein Konto?",
    dontHaveAccount: "Hast du kein Konto?",
    dataSafetyMessage:
      "Wir kümmern uns um dich und deine Informationen. Deine Daten sind bei uns sicher.",
    reasonsToStayAlive: "Gründe, um zu leben",
    uploadPhotos: "Fotos von Liebenen hochladen",
    footerMessage:
      "Wir kümmern uns um dich. Gib nicht auf - du bist bedeutend und geliebt.",
    welcome: "Du bist nicht allein",
    welcomeSubtitle:
      "Ein sicherer Ort für deine Gedanken und Gefühle",
    confessTitle: "Beichtbox",
    confessSubtitle: "Teile anonym, was dich beschäftigt",
    withAI: "Mit KI-Unterstützung",
    withoutAI: "Ohne KI",
    enterConfession: "Schreibe hier deine Gedanken...",
    submit: "Absenden",
    journalTitle: "Mein Tagebuch",
    enterPin: "4-stellige PIN eingeben",
    unlock: "Entsperren",
    moodTitle: "Wie fühlst du dich heute?",
    emergencyTitle: "Notfall-Ressourcen",
    calmingExercises: "Beruhigende Übungen",
    breathingExercise: "Atemübung",
    guidedMeditation: "Geführte Meditation",
    writeLetterTitle: "Brief Schreiben",
    writeLetterSubtitle:
      "Teile Positivität mit jemandem, der es braucht",
    readLettersTitle: "Briefe von Freunden",
    confidentialityPromise:
      "Wir versprechen, alles, was du hier teilst, vertraulich und sicher zu halten.",
    termsAndConditions:
      "Durch die Nutzung dieses Dienstes stimmst du unseren Geschäftsbedingungen zu",
    deleteNow: "Jetzt Löschen",
    deleteAfter1Hour: "Nach 1 Stunde löschen",
    deleteAfter1Week: "Nach 1 Woche löschen",
    deleteAfter1Month: "Nach 1 Monat löschen",
    aiResponse:
      "Denk daran, du bist stärker als du denkst. Jeder Schritt vorwärts, egal wie klein, ist Fortschritt.",
    crisisMessage:
      "Wenn du Gedanken an Selbstverletzung hast, suche bitte sofort Hilfe.",
    nickname: "Spitzname",
    letterFromFriendTitle: "Ein Brief von einem Freund",
    dearFriend: "Lieber Freund,",
    friendLetterPara1:
      "Ich möchte, dass du weißt: Egal, was du gerade durchmachst, du bist nicht allein. Deine Gefühle sind gültig, und es ist manchmal okay, nicht okay zu sein.",
    friendLetterPara2:
      "Denk daran, dass Stürme nicht für immer dauern. Selbst an den dunkelsten Tagen wartet Licht darauf, durchzubrechen. Du bist stärker, als du glaubst, und du verdienst Freundlichkeit, besonders von dir selbst.",
    friendLetterPara3: "Nimm es einen Moment nach dem anderen. Atme. Du schaffst das.",
    friendLetterSignature: "Mit Hoffnung und Unterstützung,\nEin Freund, der an dich denkt",
  },
  it: {
    appName: "Resta Con Me",
    home: "Home",
    confess: "Confessionale",
    journal: "Diario",
    moodTracker: "Tracker dell'Umore",
    emergency: "Risorse di Emergenza",
    writeLetter: "Scrivi una Lettera",
    readLetters: "Leggi Lettere",
    login: "Accedi",
    logout: "Esci",
    signup: "Registrati",
    firstName: "Nome",
    lastName: "Cognome",
    useAnonymousName: "Preferisco usare un nome anonimo",
    anonymousName: "Nome Anonimo/Falso",
    email: "Email",
    password: "Password",
    confirmPassword: "Conferma Password",
    createAccount: "Crea Account",
    alreadyHaveAccount: "Hai già un account?",
    dontHaveAccount: "Non hai un account?",
    dataSafetyMessage:
      "Ci preoccupiamo di te e delle tue informazioni. I tuoi dati saranno sicuri con noi.",
    reasonsToStayAlive: "Motivi per Restare in Vita",
    uploadPhotos: "Carica Foto di Persone Amate",
    footerMessage:
      "Ci preoccupiamo di te. Non te ne rendere - sei significativo e amato.",
    welcome: "Non sei solo",
    welcomeSubtitle:
      "Uno spazio sicuro per i tuoi pensieri e sentimenti",
    confessTitle: "Confessionale",
    confessSubtitle:
      "Condividi ciò che hai in mente, in modo anonimo",
    withAI: "Con Supporto AI",
    withoutAI: "Senza AI",
    enterConfession: "Scrivi i tuoi pensieri qui...",
    submit: "Invia",
    journalTitle: "Il Mio Diario",
    enterPin: "Inserisci PIN a 4 cifre",
    unlock: "Sblocca",
    moodTitle: "Come ti senti oggi?",
    emergencyTitle: "Risorse di Emergenza",
    calmingExercises: "Esercizi Calmanti",
    breathingExercise: "Esercizio di Respirazione",
    guidedMeditation: "Meditazione Guidata",
    writeLetterTitle: "Scrivi una Lettera",
    writeLetterSubtitle:
      "Condividi positività con qualcuno che ne ha bisogno",
    readLettersTitle: "Lettere dagli Amici",
    confidentialityPromise:
      "Promettiamo di mantenere tutto ciò che condividi qui confidenziale e sicuro.",
    termsAndConditions:
      "Utilizzando questo servizio, accetti i nostri Termini e Condizioni",
    deleteNow: "Elimina Ora",
    deleteAfter1Hour: "Elimina dopo 1 ora",
    deleteAfter1Week: "Elimina dopo 1 settimana",
    deleteAfter1Month: "Elimina dopo 1 mese",
    aiResponse:
      "Ricorda, sei più forte di quanto pensi. Ogni passo avanti, non importa quanto piccolo, è progresso.",
    crisisMessage:
      "Se hai pensieri di autolesionismo, cerca aiuto immediatamente.",
    nickname: "Soprannome",
    letterFromFriendTitle: "Una lettera da un amico",
    dearFriend: "Caro amico,",
    friendLetterPara1:
      "Voglio che tu sappia che, qualunque cosa tu stia attraversando in questo momento, non sei solo. I tuoi sentimenti sono validi, ed è normale non stare bene a volte.",
    friendLetterPara2:
      "Ricorda che le tempeste non durano per sempre. Anche nei giorni più bui, c'è una luce pronta a farsi strada. Sei più forte di quanto immagini, e meriti gentilezza, soprattutto da te stesso.",
    friendLetterPara3: "Affronta un momento alla volta. Respira. Ce la puoi fare.",
    friendLetterSignature: "Con speranza e sostegno,\nUn amico che ci tiene",
  },
  pt: {
    appName: "Fique Comigo",
    home: "Início",
    confess: "Caixa de Confissão",
    journal: "Diário",
    moodTracker: "Rastreador de Humor",
    emergency: "Recursos de Emergência",
    writeLetter: "Escrever uma Carta",
    readLetters: "Ler Cartas",
    login: "Entrar",
    logout: "Sair",
    signup: "Cadastrar-se",
    firstName: "Nome",
    lastName: "Sobrenome",
    useAnonymousName: "Prefiro usar um nome anônimo",
    anonymousName: "Nome Anônimo/Falso",
    email: "Email",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    createAccount: "Criar Conta",
    alreadyHaveAccount: "Já tem uma conta?",
    dontHaveAccount: "Não tem uma conta?",
    dataSafetyMessage:
      "Cuidamos de você e suas informações. Seus dados estarão seguros conosco.",
    reasonsToStayAlive: "Razões para Permanecer Vivo",
    uploadPhotos: "Carregar Fotos de Pessoas Amadas",
    footerMessage:
      "Cuidamos de você. Não desista - você é significativo e amado.",
    welcome: "Você não está sozinho",
    welcomeSubtitle:
      "Um espaço seguro para seus pensamentos e sentimentos",
    confessTitle: "Caixa de Confissão",
    confessSubtitle:
      "Compartilhe o que está em sua mente, anonimamente",
    withAI: "Com Suporte de IA",
    withoutAI: "Sem IA",
    enterConfession: "Escreva seus pensamentos aqui...",
    submit: "Enviar",
    journalTitle: "Meu Diário",
    enterPin: "Digite o PIN de 4 dígitos",
    unlock: "Desbloquear",
    moodTitle: "Como você está se sentindo hoje?",
    emergencyTitle: "Recursos de Emergência",
    calmingExercises: "Exercícios Calmantes",
    breathingExercise: "Exercício de Respiração",
    guidedMeditation: "Meditação Guiada",
    writeLetterTitle: "Escrever uma Carta",
    writeLetterSubtitle:
      "Compartilhe positividade com alguém que precisa",
    readLettersTitle: "Cartas de Amigos",
    confidentialityPromise:
      "Prometemos manter tudo o que você compartilhar aqui confidencial e seguro.",
    termsAndConditions:
      "Ao usar este serviço, você concorda com nossos Termos e Condições",
    deleteNow: "Excluir Agora",
    deleteAfter1Hour: "Excluir após 1 hora",
    deleteAfter1Week: "Excluir após 1 semana",
    deleteAfter1Month: "Excluir após 1 mês",
    aiResponse:
      "Lembre-se, você é mais forte do que pensa. Cada passo à frente, por menor que seja, é progresso.",
    crisisMessage:
      "Se você está tendo pensamentos de automutilação, procure ajuda imediatamente.",
    nickname: "Apelido",
    letterFromFriendTitle: "Uma carta de um amigo",
    dearFriend: "Querido amigo,",
    friendLetterPara1:
      "Quero que você saiba que, seja o que for que esteja passando agora, você não está sozinho. Seus sentimentos são válidos, e às vezes está tudo bem não estar bem.",
    friendLetterPara2:
      "Lembre-se de que as tempestades não duram para sempre. Mesmo nos dias mais escuros, há luz esperando para aparecer. Você é mais forte do que imagina e merece gentileza, especialmente de si mesmo.",
    friendLetterPara3: "Vá um momento de cada vez. Respire. Você consegue.",
    friendLetterSignature: "Com esperança e apoio,\nUm amigo que se importa",
  },
  hi: {
    appName: "मेरे साथ रहो",
    home: "होम",
    confess: "कन्फेशन बॉक्स",
    journal: "जर्नल",
    moodTracker: "मूड ट्रैकर",
    emergency: "आपातकालीन संसाधन",
    writeLetter: "पत्र लिखें",
    readLetters: "पत्र पढ़ें",
    login: "लॉगिन",
    logout: "लॉगआउट",
    signup: "साइन अप",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    useAnonymousName:
      "मैं एक गुमनाम नाम का उपयोग करना पसंद करता हूँ",
    anonymousName: "गुमनाम/झूठा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुनः पुष्टि करें",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "आपका पहले से ही खाता है?",
    dontHaveAccount: "आपका खाता नहीं है?",
    dataSafetyMessage:
      "हम आपकी और आपकी जानकारी पर ध्यान रखते हैं। आपके डेटा हमारे साथ सुरक्षित होंगे।",
    reasonsToStayAlive: "जीवन रखने के कारण",
    uploadPhotos: "प्रेमितों की फोटो अपलोड करें",
    footerMessage:
      "हम आपकी पर ध्यान रखते हैं। न रोकें - आप महत्वपूर्ण और प्यार का हैं।",
    welcome: "आप अकेले नहीं हैं",
    welcomeSubtitle:
      "आपके विचारों और भावनाओं के लिए एक सुरक्षित स्थान",
    confessTitle: "कन्फेशन बॉक्स",
    confessSubtitle: "अपने मन की बात गुमनाम रूप से साझा करें",
    withAI: "AI सपोर्ट के साथ",
    withoutAI: "AI के बिना",
    enterConfession: "यहां अपने विचार लिखें...",
    submit: "सबमिट करें",
    journalTitle: "मेरी डायरी",
    enterPin: "4 अंकों का पिन दर्ज करें",
    unlock: "अनलॉक करें",
    moodTitle: "आज आप कैसा महसूस कर रहे हैं?",
    emergencyTitle: "आपातकालीन संसाधन",
    calmingExercises: "शांत करने वाले व्यायाम",
    breathingExercise: "श्वास व्यायाम",
    guidedMeditation: "निर्देशित ध्यान",
    writeLetterTitle: "पत्र लिखें",
    writeLetterSubtitle:
      "किसी ऐसे व्यक्ति के साथ सकारात्मकता साझा करें जिसे इसकी आवश��कता है",
    readLettersTitle: "दोस्तों के पत्र",
    confidentialityPromise:
      "हम वादा करते हैं कि आप यहां जो कुछ भी साझा करेंगे उसे गोपनीय और सुरक्षित रखा जाएगा।",
    termsAndConditions:
      "इस सेवा का उपयोग करके, आप हमारे नियमों और शर्तों से सहमत होते हैं",
    deleteNow: "अभी हटाएं",
    deleteAfter1Hour: "1 घंटे बाद हटाएं",
    deleteAfter1Week: "1 सप्ताह बाद हटाएं",
    deleteAfter1Month: "1 महीने बाद हटाएं",
    aiResponse:
      "याद रखें, आप जितना सोचते हैं उससे कहीं ज्यादा मजबूत हैं। आगे बढ़ा हर कदम, चाहे वह कितना भी छोटा क्यों न हो, प्रगति है।",
    crisisMessage:
      "यदि आपके मन में आत्म-हानि के विचार आ रहे हैं, तो कृपया तुरंत मदद लें।",
    nickname: "उपनाम",
    letterFromFriendTitle: "एक दोस्त का पत्र",
    dearFriend: "प्रिय दोस्त,",
    friendLetterPara1:
      "मैं चाहता/चाहती हूँ कि तुम जानो, अभी तुम जो भी झेल रहे हो, उसमें तुम अकेले नहीं हो। तुम्हारी भावनाएँ सही हैं, और कभी-कभी ठीक न होना भी ठीक है।",
    friendLetterPara2:
      "याद रखो, तूफान हमेशा नहीं रहते। सबसे अंधेरे दिनों में भी रोशनी रास्ता बना लेती है। तुम सोचते हो उससे ज्यादा मजबूत हो, और तुम दयालुता के हकदार हो, खासकर अपनी तरफ से।",
    friendLetterPara3: "एक-एक पल करके आगे बढ़ो। सांस लो। तुम कर सकते हो।",
    friendLetterSignature: "उम्मीद और साथ के साथ,\nएक दोस्त जो ख्याल रखता है",
  },
  zh: {
    appName: "与��同在",
    home: "首页",
    confess: "倾诉箱",
    journal: "日记",
    moodTracker: "心情追踪",
    emergency: "紧急资源",
    writeLetter: "写信",
    readLetters: "读信",
    login: "登录",
    logout: "登出",
    signup: "注册",
    firstName: "名字",
    lastName: "姓氏",
    useAnonymousName: "我更喜欢使用匿名名字",
    anonymousName: "匿名/假名",
    email: "电子邮件",
    password: "密码",
    confirmPassword: "确认密码",
    createAccount: "创建账户",
    alreadyHaveAccount: "已经有账户？",
    dontHaveAccount: "没有账户？",
    dataSafetyMessage:
      "我们关心你和你的信息。你的数据将由我们安全保管。",
    reasonsToStayAlive: "生存的理由",
    uploadPhotos: "上传你爱的人的照片",
    footerMessage: "我们关心你。不要放弃 - 你很重要且被爱。",
    welcome: "你并不孤单",
    welcomeSubtitle: "一个安全的空间，倾诉你的想法和感受",
    confessTitle: "倾诉箱",
    confessSubtitle: "匿名分享你的心事",
    withAI: "AI 支持",
    withoutAI: "无 AI",
    enterConfession: "在此写下你的想法...",
    submit: "提交",
    journalTitle: "我的日记",
    enterPin: "输入4位数密码",
    unlock: "解锁",
    moodTitle: "你今感觉如何？",
    emergencyTitle: "紧急资源",
    calmingExercises: "平静练习",
    breathingExercise: "呼吸练习",
    guidedMeditation: "引导冥想",
    writeLetterTitle: "写信",
    writeLetterSubtitle: "与需要的人分享正能量",
    readLettersTitle: "来自朋友的信",
    confidentialityPromise: "我们承诺对你在此分享的一切保密。",
    termsAndConditions:
      "使用此服务即表示您同意我们的条款和条件",
    deleteNow: "立即删除",
    deleteAfter1Hour: "1小时后删除",
    deleteAfter1Week: "1周后删除",
    deleteAfter1Month: "1个月后删除",
    aiResponse:
      "记住，你比你想象的更坚强。每一步前进，无论多小，都是进步。",
    crisisMessage: "如果你有自残的想法，请立即寻求帮助。",
    nickname: "昵称",
    letterFromFriendTitle: "来自朋友的一封信",
    dearFriend: "亲爱的朋友，",
    friendLetterPara1:
      "我想让你知道，无论你现在正在经历什么，你都不孤单。你的感受是真实且被理解的，有时候状态不好也没关系。",
    friendLetterPara2:
      "请记住，风暴不会永远持续。即使在最黑暗的日子里，也有光在等待出现。你比自己想象的更坚强，你值得被善待，尤其要善待自己。",
    friendLetterPara3: "一步一步来。深呼吸。你一定可以。",
    friendLetterSignature: "带着希望与支持，\n一位关心你的朋友",
  },
  ja: {
    appName: "私と一緒にいて",
    home: "ホーム",
    confess: "告白ボックス",
    journal: "日記",
    moodTracker: "気分トラッカー",
    emergency: "緊急リソース",
    writeLetter: "手紙を書く",
    readLetters: "手紙を読む",
    login: "ログイン",
    logout: "ログアウト",
    signup: "登録",
    firstName: "名前",
    lastName: "姓",
    useAnonymousName: "匿名の名前を使用したい",
    anonymousName: "匿名/偽名",
    email: "メール",
    password: "パスワード",
    confirmPassword: "パスワードを確認",
    createAccount: "アカウントを作成",
    alreadyHaveAccount: "既にアカウントがありますか？",
    dontHaveAccount: "アカウントがありませんか？",
    dataSafetyMessage:
      "あなたとあなたの情報を心配しています。あなたのデータは私たちによって安全に保管されます。",
    reasonsToStayAlive: "生きる理由",
    uploadPhotos: "愛する人の写真をアップロード",
    footerMessage:
      "あなたを心配しています。諦めないでください - あなたは重要で愛されています。",
    welcome: "あなたは一人じゃない",
    welcomeSubtitle: "あなたの考えや感情のための安全な場所",
    confessTitle: "告白ボックス",
    confessSubtitle: "心の中を匿名で共有してください",
    withAI: "AIサポート付き",
    withoutAI: "AIなし",
    enterConfession: "ここにあなたの思いを書いてください...",
    submit: "送信",
    journalTitle: "私の日記",
    enterPin: "4桁のPINを入力",
    unlock: "ロック解除",
    moodTitle: "今日の気分は？",
    emergencyTitle: "緊急リソース",
    calmingExercises: "落ち着く練習",
    breathingExercise: "呼吸法",
    guidedMeditation: "ガイド付き瞑想",
    writeLetterTitle: "手紙を書く",
    writeLetterSubtitle:
      "必要としている誰かとポジティブさを共有する",
    readLettersTitle: "友達からの手紙",
    confidentialityPromise:
      "ここで共有されたすべてを機密かつ安全に保つことを約束します。",
    termsAndConditions:
      "このサービスを使用することにより、利用規約に同意したことになります",
    deleteNow: "今すぐ削除",
    deleteAfter1Hour: "1時間後に削除",
    deleteAfter1Week: "1週間後に削除",
    deleteAfter1Month: "1ヶ月後に削除",
    aiResponse:
      "覚えておいて、あなたは思っているよりも強いです。どんなに小さくても、前進する一歩一歩が進歩です。",
    crisisMessage:
      "自傷行為の考えがある場合は、すぐに助けを求めてください。",
    nickname: "ニックネーム",
    letterFromFriendTitle: "友だちからの手紙",
    dearFriend: "親愛なる友だちへ、",
    friendLetterPara1:
      "今あなたがどんな状況にいても、ひとりではないことを知ってほしいです。あなたの気持ちは大切で、つらいと感じることがあっても大丈夫です。",
    friendLetterPara2:
      "嵐はずっと続きません。どんなに暗い日にも、差し込む光があります。あなたは自分が思うよりずっと強く、特に自分自身に優しくされる価値があります。",
    friendLetterPara3: "一瞬ずつで大丈夫。深呼吸して。あなたならできる。",
    friendLetterSignature: "希望と応援をこめて、\nあなたを気にかける友だちより",
  },
  ar: {
    appName: "ابق معي",
    home: "الرئيسية",
    confess: "صندوق الاعتراف",
    journal: "المذكرات",
    moodTracker: "متتبع المزاج",
    emergency: "موارد الطوارئ",
    writeLetter: "اكتب رسالة",
    readLetters: "اقرأ الرسائل",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    signup: "إنشاء حساب",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    useAnonymousName: "أفضل لي استخدام اسم مجهول",
    anonymousName: "اسم مجهول/خاطئ",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    dataSafetyMessage:
      "نحن نهتم بك وبياناتك. سيتم حفظ بياناتك بأمان معنا.",
    reasonsToStayAlive: "أسباب للبقاء على قيد الحياة",
    uploadPhotos: "تحميل صور الأشخاص الذين تحبه",
    footerMessage: "نحن نهتم بك. لا تردد - أنت مهم ومحبوب.",
    welcome: "أنت لست وحدك",
    welcomeSubtitle: "مساحة آمنة لأفكارك ومشاعرك",
    confessTitle: "صندوق الاعتراف",
    confessSubtitle: "شارك ما يدور في ذهنك بشكل مجهول",
    withAI: "مع دعم الذكاء الاصطناعي",
    withoutAI: "بدون ذكاء اصطناعي",
    enterConfession: "اكتب أفكارك هنا...",
    submit: "إرسال",
    journalTitle: "مذكراتي",
    enterPin: "أدخل رمز PIN المكون من 4 أرقام",
    unlock: "فتح",
    moodTitle: "كيف تشعر اليوم؟",
    emergencyTitle: "موارد الطوارئ",
    calmingExercises: "تمارين التهدئة",
    breathingExercise: "تمرين التنفس",
    guidedMeditation: "التأمل الموجه",
    writeLetterTitle: "اكتب رسالة",
    writeLetterSubtitle: "شارك الإيجابية مع شخص يحتاجها",
    readLettersTitle: "رسائل من الأصدقاء",
    confidentialityPromise:
      "نعدك بأن نحافظ على سرية وأمان كل ما تشاركه هنا.",
    termsAndConditions:
      "باستخدام هذه الخدمة، فإنك توافق على الشروط والأحكام الخاصة بنا",
    deleteNow: "احذف الآن",
    deleteAfter1Hour: "احذف بعد ساعة",
    deleteAfter1Week: "احذف بعد أسبوع",
    deleteAfter1Month: "احذف بعد شهر",
    aiResponse:
      "تذكر، أنت أقوى مما تعتقد. كل خطوة إلى الأمام، مهما كانت صغيرة، هي تقدم.",
    crisisMessage:
      "إذا كانت لديك أفكار إيذاء النفس، يرجى طلب المساعدة على الفور.",
    nickname: "الاسم المستعار",
    letterFromFriendTitle: "رسالة من صديق",
    dearFriend: "صديقي العزيز،",
    friendLetterPara1:
      "أريدك أن تعرف أنه مهما كان ما تمر به الآن، فأنت لست وحدك. مشاعرك حقيقية ومهمة، ومن الطبيعي أحيانًا ألا تكون بخير.",
    friendLetterPara2:
      "تذكر أن العواصف لا تدوم إلى الأبد. حتى في أكثر الأيام ظلامًا، هناك نور ينتظر أن يظهر. أنت أقوى مما تظن، وتستحق اللطف، خاصة من نفسك.",
    friendLetterPara3: "خذها لحظة بلحظة. تنفس. أنت قادر على ذلك.",
    friendLetterSignature: "مع الأمل والدعم،\nصديق يهتم بك",
  },
  ne: {
    appName: "मेरोसँग",
    home: "गृहपृष्ठ",
    confess: "स्वीकारोक्ति",
    journal: "मेरो डायरी",
    moodTracker: "मूड ट्र्याकर",
    emergency: "आपतकालीन सहयोग",
    writeLetter: "पत्र लेख्नुहोस्",
    readLetters: "पत्रहरू पढ्नुहोस्",
    login: "लगइन",
    logout: "लगआउट",
    signup: "साइन अप",
    firstName: "पहिलो नाम",
    lastName: "थरो नाम",
    useAnonymousName:
      "मलाई अनामिक नाम प्रयोग गर्न सुनिश्चित छु",
    anonymousName: "अनामिक/झूठो नाम",
    email: "इमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड पुनः पुष्टि गर्नुहोस्",
    createAccount: "खाता बनाउनुहोस्",
    alreadyHaveAccount: "तपाईंको पहिले से ही खाता छ?",
    dontHaveAccount: "तपाईंको खाता छैन?",
    dataSafetyMessage:
      "हामी तपाईं र तपाईंको जानकारी पर ध्यान रख्छु। तप��ईंको डेटा हामीको साथ सुरक्षित हुन्छ।",
    reasonsToStayAlive: "जीवन रख्ने कारणहरू",
    uploadPhotos: "प्रेमितोंको फोटोहरू अपलोड गर्नुहोस्",
    footerMessage:
      "हामी तपाईं पर ध्यान रख्छु। न रोक्नुहोस् - तपाईं महत्वपूर्ण र प्यार का हुन्छ।",
    welcome: "तिमी एक्लो छैनौ",
    welcomeSubtitle:
      "तिम्रा विचार र भावनाका लागि सुरक्षित स्थान",
    confessTitle: "स्वीकारोक्ति बाकस",
    confessSubtitle: "मनमा जे छ, यहाँ गुमनाम रूपमा लेख",
    withAI: "एआई सहयोगसहित",
    withoutAI: "एआई सहयोगबिना",
    enterConfession: "यहाँ आफ्नो मनको कुरा लेख...",
    submit: "पेश गर्नुहोस्",
    journalTitle: "मेरो डायरी",
    enterPin: "४ अङ्कको PIN प्रविष्ट गर्नुहोस्",
    unlock: "अनलक गर्नुहोस्",
    moodTitle: "आज तिमी कस्तो महसुस गर्दैछौ?",
    emergencyTitle: "आपतकालीन स्रोतहरू",
    calmingExercises: "शान्त बनाउने अभ्यासहरू",
    breathingExercise: "श्वास अभ्यास",
    guidedMeditation: "निर्देशित ध्यान",
    writeLetterTitle: "पत्र लेख्नुहोस्",
    writeLetterSubtitle:
      "कसैलाई सकारात्मक सन्देश पठाउनुहोस् जसलाई यसको आवश्यकता छ",
    readLettersTitle: "साथीहरूका पत्रहरू",
    confidentialityPromise:
      "हामी यहाँ तिमीले साझा गरेका सबै कुरा गोप्य र सुरक्षित राख्ने वाचा गर्छौं।",
    termsAndConditions:
      "यो सेवा प्रयोग गरेर, तिमीले हाम्रा सर्तहरू र गोपनीयता नीतिमा सहमति जनाउँछौ।",
    deleteNow: "अहिले मेटाउनुहोस्",
    deleteAfter1Hour: "१ घण्टापछि मेटाउनुहोस्",
    deleteAfter1Week: "१ हप्तापछि मेटाउनुहोस्",
    deleteAfter1Month: "१ महिनापछि मेटाउनुहोस्",
    aiResponse:
      "सम्झ, तिमीले सोचेभन्दा धेरै बलियो छौ। अगाडि बढेको हरेक सानो पाइला पनि प्रगति हो।",
    crisisMessage:
      "यदि तिमीलाई आत्म-हानि वा आत्महत्याका विचार आइरहेका छन् भने, कृपया तुरुन्त मद्दत खोज।",
    nickname: "उपनाम",
    invalidEmailError: "कृपया मान्य इमेल ठेगाना प्रविष्ट गर्नुहोस्",
    enterPasswordError: "कृपया आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्",
    welcomeBack: "फेरि स्वागत छ!",
    enterFirstLastError: "कृपया आफ्नो पहिलो नाम र थर प्रविष्ट गर्नुहोस्",
    enterAnonymousNameError: "कृपया एउटा अनामिक नाम प्रविष्ट गर्नुहोस्",
    passwordPolicyError:
      "पासवर्ड कम्तीमा ८ अक्षरको, ठूलो अक्षर, सानो अक्षर, अंक र विशेष चिन्ह भएको हुनुपर्छ",
    passwordsDoNotMatch: "पासवर्डहरू मिलेनन्",
    agreeTermsError: "कृपया सर्तहरूमा सहमति जनाउनुहोस्",
    signinSubtitle: "आफ्नो खातामा साइन इन गर्नुहोस्",
    signupSubtitle: "आफ्नो सुरक्षित स्थानको खाता बनाउनुहोस्",
    emailPlaceholder: "your.email@example.com",
    passwordPlaceholder: "••••••••",
    firstNamePlaceholder: "पहिलो नाम",
    lastNamePlaceholder: "थर",
    anonymousNamePlaceholder: "Phoenix, Shadow, आदि",
    passwordRulesHint: "कम्तीमा ८ अक्षर, A-Z, a-z, 0-9, @$!%*?&",
    confirmPasswordPlaceholder: "पासवर्ड फेरि लेख्नुहोस्",
    authPrivacyFooter:
      "तपाईंको इमेल प्रमाणीकरणका लागि मात्र प्रयोग हुन्छ। तपाईंलाई अनियमित उपनामबाट चिनिनेछ।",
    homePositiveMessage: "तिमी सोचेभन्दा धेरै बलियो छौ",
    homeJournalDesc: "PIN सुरक्षासहित निजी र सुरक्षित डायरी",
    homeMoodDesc: "आफ्नो भावनात्मक यात्रा ट्र्याक गर",
    homeEmergencyDesc: "श्वास अभ्यास र शान्त बनाउने स्रोतहरू",
    homeReasonsDesc: "जीवन सुन्दर बनाउने कारणहरू सम्झ",
    homeReadLettersDesc: "अरूबाट आएका उत्साहजनक सन्देशहरू पढ",
    homeSafeSpaceTitle: "तिम्रो सुरक्षित स्थान",
    homeSafeSpaceSubtitle: "जुन सहयोग चाहिन्छ, त्यही बेला छान",
    pleaseSelectMood: "कृपया मूड छान्नुहोस्",
    moodTracked: "मूड सुरक्षित गरियो!",
    selectYourMood: "आफ्नो मूड छान्नुहोस्",
    addNoteOptional: "एउटा नोट थप्नुहोस् (वैकल्पिक)",
    whatsOnYourMind: "तिम्रो मनमा के छ?",
    saveMood: "मूड सुरक्षित गर्नुहोस्",
    yourMoodHistory: "तिम्रो मूड इतिहास",
    noMoodEntriesYet: "अहिलेसम्म कुनै मूड इन्ट्री छैन। सुरु गर!",
    moodGreat: "धेरै राम्रो",
    moodGood: "राम्रो",
    moodOkay: "ठिकठाक",
    moodBad: "खराब",
    moodTerrible: "धेरै खराब",
    pinMustBe4Digits: "PIN ४ अङ्कको हुनुपर्छ",
    journalPinSetSuccess: "जर्नल PIN सफलतापूर्वक सेट भयो",
    incorrectPin: "गलत PIN",
    pleaseWriteSomething: "कृपया केही लेख्नुहोस्",
    entrySaved: "इन्ट्री सुरक्षित गरियो",
    entryDeleted: "इन्ट्री मेटाइयो",
    youAreNotAloneReachOut: "तिमी एक्लो छैनौ। कृपया सहयोग गर्न सक्ने कसैलाई सम्पर्क गर।",
    viewEmergencyResources: "आपतकालीन स्रोतहरू हेर्नुहोस्",
    goBack: "फर्कनुहोस्",
    journalPrivateSecureSpace: "तिम्रो निजी, सुरक्षित स्थान",
    enterPinToAccessJournal: "जर्नल पहुँच गर्न आफ्नो PIN प्रविष्ट गर",
    setPinToProtectJournal: "जर्नल सुरक्षित गर्न ४ अङ्कको PIN सेट गर",
    lock: "लक",
    journalSanctuary: "तिम्रा विचारहरू, तिम्रो सुरक्षित ठाउँ",
    newEntry: "नयाँ इन्ट्री",
    writeThoughtsHere: "यहाँ आफ्ना विचारहरू लेख...",
    addEntry: "इन्ट्री थप्नुहोस्",
    noEntriesYetStartWriting: "अहिलेसम्म इन्ट्री छैन। लेख्न सुरु गर!",
    pleaseWriteAtLeast20Chars: "कृपया कम्तीमा २० अक्षर लेख्नुहोस्",
    positiveWordsOnly: "कृपया सकारात्मक र उत्साहजनक शब्द मात्र प्रयोग गर्नुहोस्",
    anonymous: "अनामिक",
    letterSharedSuccess: "तिम्रो पत्र साझा गरियो! सकारात्मकता फैलाएकोमा धन्यवाद।",
    writeYourLetter: "आफ्नो पत्र लेख",
    writeLetterGuidance:
      "उत्साह, आशा र सकारात्मकताका शब्दहरू लेख। तिम्रो पत्रले कसैको दिन उज्यालो बनाउन सक्छ।",
    writeLetterPlaceholder: "प्रिय साथी,\n\nम तिमीलाई भन्न चाहन्छु कि...",
    charactersMinimum20: "अक्षर (कम्तीमा २०)",
    fromLabel: "बाट:",
    guidelines: "निर्देशनहरू:",
    guidelinePositiveWords: "सकारात्मक र उत्साहजनक शब्द मात्र प्रयोग गर",
    guidelineGenuine: "साँचो र मनदेखि लेख",
    guidelineFriendInNeed: "सहयोग चाहिने साथीलाई लेखेजस्तो सोच",
    guidelineAnonymousShare: "तिम्रो पत्र उपनामसहित अनामिक रूपमा साझा गरिनेछ",
    sendLetter: "पत्र पठाउनुहोस्",
    readLettersFromOthers: "अरूका पत्रहरू पढ्नुहोस्",
    noLettersYet: "अहिलेसम्म कुनै पत्र छैन",
    beFirstToSharePositivity: "सकारात्मक सन्देश साझा गर्ने पहिलो बन्नुहोस्!",
    readLettersSubtitle: "ख्याल गर्ने अन्जान साथीहरूबाट आशाका सन्देशहरू",
    previous: "अघिल्लो",
    random: "अनियमित",
    next: "अर्को",
    shareOwnMessageCta: "आफ्नै आशाको सन्देश साझा गर्न चाहन्छौ?",
    maxPhotosError: "तपाईंले बढीमा {max} वटा फोटो मात्र अपलोड गर्न सक्नुहुन्छ",
    photosUploaded: "फोटोहरू अपलोड भए!",
    reasonsSubtitle: "जीवन सुन्दर बनाउने क्षणहरू र मानिसहरू सम्झनुहोस्",
    uploadPhotosHelp:
      "प्रियजन, जनावर, मनपर्ने ठाउँ वा खुशी दिने कुनै पनि तस्बिर अपलोड गर्नुहोस्।",
    choosePhotos: "फोटो छान्नुहोस्",
    continueToVideos: "प्रेरणादायी भिडियोहरूमा जानुहोस्",
    wordsOfHope: "आशा र उत्साहका शब्दहरू",
    wordsOfHopeDesc: "आशा, धैर्य र जीवनको मूल्यबारे शक्तिशाली सन्देशहरू हेर्नुहोस्।",
    footerStrengthLine:
      "तिमीले सोचेभन्दा बलियो, विश्वास गरेभन्दा साहसी र बुझेकाभन्दा धेरै प्रेमिल छौ।",
    youMatterTitle: "तिमी महत्वपूर्ण छौ",
    youMatterDesc: "जीवनको मूल्य र उद्देश्य छ, देख्न गाह्रो भए पनि।",
    youreNotAloneTitle: "तिमी एक्लो छैनौ",
    youreNotAloneDesc: "हामी तिम्रो साथमा छौं, र धेरै मानिसहरू तिम्रो ख्याल राख्छन्।",
    hopeExistsTitle: "आशा छ",
    hopeExistsDesc: "सबै कुरा सुधारिन्छ। भोलि नयाँ अवसर हो।",
    ifInCrisisReachOut: "यदि संकटमा छौ भने, कृपया सम्पर्क गर:",
    safeSpaceMentalHealth: "मानसिक स्वास्थ्य सहयोगका लागि सुरक्षित स्थान",
    footerQuote:
      "\"जाडोको बीचमा, मैले आफ्नै भित्र अजेय गर्मी भेटेँ।\" - अल्बेर कामु",
    pinSetSuccess: "PIN सफलतापूर्वक सेट भयो",
    enterPinToAccess: "पहुँच गर्न PIN प्रविष्ट गर",
    setPinToProtectConfessions: "स्वीकारोक्ति सुरक्षित गर्न ४ अङ्कको PIN सेट गर",
    chooseYourMode: "आफ्नो मोड छान",
    withAIDesc: "AI बाट उत्साहजनक सन्देश पाउनुहोस्",
    withoutAIDesc: "आफ्ना विचारहरू निजी रूपमा साझा गर्नुहोस्",
    deleteOption: "मेटाउने विकल्प",
    back: "फर्कनुहोस्",
    heresSomethingForYou: "तिम्रो लागि एउटा कुरा",
    letterFromFriendTitle: "एउटा साथीको पत्र",
    dearFriend: "प्रिय साथी,",
    friendLetterPara1: 
      "अहिले तिमी जे भोग्दैछौ, त्यसमा तिमी एक्लो छैनौ। तिम्रा भावना मान्य छन्। कहिलेकाहीँ ठीक नहुनु पनि ठीक हो।",
    friendLetterPara2: 
      "आँधी सधैं रहँदैन। अँध्यारो दिनमा पनि उज्यालो आउँछ। तिमी सोचेभन्दा बलियो छौ, र तिमीले आफूबाटै दया पाउन योग्य छौ।",
    friendLetterPara3: "एक-एक पल गर्दै अगाडि बढ। सास फेर। तिमी सक्छौ।",
    friendLetterSignature: "आशा र साथसहित,\nख्याल राख्ने साथी",
    aiSupportMessage: "AI सहयोग सन्देश",
    goHome: "गृहपृष्ठ",
    newConfession: "नयाँ स्वीकारोक्ति",
    emergencySubtitle: "शान्त र स्थिर हुन मद्दत गर्ने उपकरणहरू",
    ifInCrisis: "यदि तिमी संकटमा छौ",
    pleaseReachImmediateHelp: "तुरुन्त सहयोग खोज्नुहोस्। तिमी एक्लो छैनौ।",
    boxBreathingTitle: "बक्स ब्रीदिङ (४-४-४-४)",
    boxBreathingDesc: "दबाबमा पनि शान्त रहन प्रयोग हुने प्रभावकारी अभ्यास",
    breatheIn: "सास भित्र",
    hold: "रोक",
    breatheOut: "सास बाहिर",
    fourSeconds: "४ सेकेन्ड",
    stop: "रोक्नुहोस्",
    start: "सुरु गर्नुहोस्",
    howItWorks: "यसरी काम गर्छ:",
    breatheIn4: "४ सेकेन्ड सास भित्र तान",
    hold4: "४ सेकेन्ड सास रोक",
    breatheOut4: "४ सेकेन्ड सास बाहिर छोड",
    rest4: "४ सेकेन्ड विश्राम (चक्रमा समावेश)",
    repeatAsNeeded: "आवश्यक अनुसार दोहोर्याउनुहोस्",
  },
};

const LanguageContext = createContext<
  LanguageContextType | undefined
>(undefined);

export function LanguageProvider({
  children,
}: {
  children: ReactNode;
}) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("staywithme_language") as Language | null;
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("staywithme_language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error(
      "useLanguage must be used within LanguageProvider",
    );
  }
  return context;
}
