/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId =
  import.meta.env.VITE_SUPABASE_URL || "dhijbciikxrnbjtcjxag";
export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "sb_publishable_tdYXeBMkT2W66PHqBPqNgA_wYAugwfs";
